export const HANDLE_ON_QUESTIONS='HANDLE_ON_QUESTIONS';
export const HANDLE_ON_TOGGLE_DIALOG='HANDLE_ON_TOGGLE_DIALOG';
export const HANDLE_ON_POSTS='HANDLE_ON_POSTS';
export const HANDLE_FIELD_CHANGE='HANDLE_FIELD_CHANGE';
export const HANDLE_ON_CLICK_DELETE_POST='HANDLE_ON_CLICK_DELETE_POST';
export const HANDLE_FIELD_CHANGE_NUMBER='HANDLE_FIELD_CHANGE_NUMBER';
export const HANDLE_CHANGE_OPTION='HANDLE_CHANGE_OPTION';
